#ifndef COM_FILEHELPER_GLOBAL_H
#define COM_FILEHELPER_GLOBAL_H


#include <QtCore/qglobal.h>

#if defined(COM_FILEHELPER_LIBRARY)
#  define COM_FILEHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COM_FILEHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILEHELPER_GLOBAL_H
