#ifndef COM_LOGICEXCEPTION_GLOBAL_H
#define COM_LOGICEXCEPTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOGICEXCEPTION_LIBRARY)
#  define LOGICEXCEPTION_EXPORT Q_DECL_EXPORT
#else
#  define LOGICEXCEPTION_EXPORT Q_DECL_IMPORT
#endif

#endif // LOGICEXCEPTION_GLOBAL_H
