#ifndef TEXTFILEHELPER_GLOBAL_H
#define TEXTFILEHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEXTFILEHELPER_LIBRARY)
#  define TEXTFILEHELPER_EXPORT Q_DECL_EXPORT
#else
#  define TEXTFILEHELPER_EXPORT Q_DECL_IMPORT
#endif

#endif // TEXTFILEHELPER_GLOBAL_H
