#ifndef COMMANDLINEPARSERHELPER_GLOBAL_H
#define COMMANDLINEPARSERHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMANDLINEPARSERHELPER_LIBRARY)
#  define COMMANDLINEPARSERHELPER_EXPORT Q_DECL_EXPORT
#else
#  define COMMANDLINEPARSERHELPER_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMANDLINEPARSERHELPER_GLOBAL_H
