#ifndef COM_MACROFACTORY_GLOBAL_H
#define COM_MACROFACTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MACROFACTORY_LIBRARY)
#  define MACROFACTORYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MACROFACTORYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MACROFACTORY_GLOBAL_H
