#ifndef COM_SIGNALHELPER_GLOBAL_H
#define COM_SIGNALHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COM_SIGNALHELPER_LIBRARY)
#  define COM_SIGNALHELPER_EXPORT Q_DECL_EXPORT
#else
#  define COM_SIGNALHELPER_EXPORT Q_DECL_IMPORT
#endif

#endif // SIGNALHELPER_GLOBAL_H
