#ifndef STRINGHELPER_GLOBAL_H
#define STRINGHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STRINGHELPER_LIBRARY)
#  define STRINGHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STRINGHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STRINGHELPER_GLOBAL_H

