#ifndef COM_FILENAMEHELPER_GLOBAL_H
#define COM_FILENAMEHELPER_GLOBAL_H


#include <QtCore/qglobal.h>

#if defined(COM_FILENAMEHELPER_LIBRARY)
#  define COM_FILENAMEHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COM_FILENAMEHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILENAMEHELPER_GLOBAL_H
