#ifndef COM_PROCESSHELPER_GLOBAL_H
#define COM_PROCESSHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COM_PROCESSHELPER_LIBRARY)
#  define COM_PROCESSHELPER_EXPORT Q_DECL_EXPORT
#else
#  define COM_PROCESSHELPER_EXPORT Q_DECL_IMPORT
#endif

#endif // COM_PROCESSHELPER_GLOBAL_H
