#ifndef COM_COREAPPWORKER_GLOBAL_H
#define COM_COREAPPWORKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COM_COREAPPWORKER_LIBRARY)
#  define COM_COREAPPWORKER_EXPORT Q_DECL_EXPORT
#else
#  define COM_COREAPPWORKER_EXPORT Q_DECL_IMPORT
#endif

#endif // COREAPPWORKER_GLOBAL_H
