#ifndef COREAPPWORKER_GLOBAL_H
#define COREAPPWORKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COREAPPWORKER_LIBRARY)
#  define COREAPPWORKER_EXPORT Q_DECL_EXPORT
#else
#  define COREAPPWORKER_EXPORT Q_DECL_IMPORT
#endif

#endif // COREAPPWORKER_GLOBAL_H
