#ifndef COM_SETTINGSHELPER_GLOBAL_H
#define COM_SETTINGSHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COM_SETTINGSHELPER_LIBRARY)
#  define COM_SETTINGSHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COM_SETTINGSHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SETTINGSHELPER_GLOBAL_H
