#ifndef COM_NETWORKHELPER_GLOBAL_H
#define COM_NETWORKHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COM_NETWORKHELPER_LIBRARY)
#  define COM_NETWORKHELPER_EXPORT Q_DECL_EXPORT
#else
#  define COM_NETWORKHELPER_EXPORT Q_DECL_IMPORT
#endif

#endif // COM_NETWORKHELPER_GLOBAL_H
