#ifndef COM_SETTINGSHELPER_GLOBAL_H
#define COM_SETTINGSHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SETTINGSHELPER_LIBRARY)
#  define SETTINGSHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SETTINGSHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SETTINGSHELPER_GLOBAL_H
